extensions:
  health_check:

receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:1010

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  awss3:
    s3uploader:
      region: 'eu-central-1'
      s3_bucket: 'opencti-bucket'
      s3_prefix: 'telemetry'
      s3_partition: 'minute'
      file_prefix: 'telemetry'
      endpoint: 0.0.0.0:8889

service:

  pipelines:

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, awss3]

  extensions: [health_check]