extensions:
  health_check:

receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:1010

processors:
  batch:

exporters:
  debug:
    verbosity: detailed

service:

  pipelines:

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]

  extensions: [health_check]