---
kind: pipeline
name: opencti-tests

steps:
  - name: build-circleci-release
    image: curlimages/curl
    commands:
      - curl -X POST --data "tag=$DRONE_TAG" https://circleci.com/api/v1.1/project/github/OpenCTI-Platform/opencti/build?circle-token=$CIRCLECI_TOKEN
    environment:
      CIRCLECI_TOKEN:
        from_secret: circleci_token
    when:
      event:
        - tag

volumes:
  - name: cache-node-backend
    host:
      path: /tmp/cache-node-backend
  - name: cache-node-raw-start-backend
    host:
      path: /tmp/cache-node-raw-start-backend
  - name: cache-node-live-start-backend
    host:
      path: /tmp/cache-node-live-start-backend
  - name: cache-node-direct-start-backend
    host:
      path: /tmp/cache-node-direct-start-backend
  - name: cache-node-restore-start-backend
    host:
      path: /tmp/cache-node-restore-start-backend
  - name: cache-node-e2e-start-backend
    host:
      path: /tmp/cache-node-e2e-start-backend
  - name: cache-node-frontend
    host:
      path: /tmp/cache-node-frontend
  - name: cache-node-frontend-e2e
    host:
      path: /tmp/cache-node-frontend-e2e
  - name: cache-python-worker
    host:
      path: /tmp/cache-python-worker      
  - name: cache-python-backend
    host:
      path: /tmp/cache-python-backend
  - name: cache-python-frontend
    host:
      path: /tmp/cache-python-frontend
  - name: cache-python-frontend-e2e
    host:
      path: /tmp/cache-python-frontend-e2e
  - name: cache-python-raw-start-backend
    host:
      path: /tmp/cache-python-raw-start-backend
  - name: cache-python-live-start-backend
    host:
      path: /tmp/cache-python-live-start-backend
  - name: cache-python-direct-start-backend
    host:
      path: /tmp/cache-python-direct-start-backend
  - name: cache-python-restore-start-backend
    host:
      path: /tmp/cache-python-restore-start-backend
  - name: cache-python-e2e-start-backend
    host:
      path: /tmp/cache-python-e2e-start-backend