kind: pipeline
name: opencti-tests

steps:
- name: api-tests
  image: nikolaik/python-nodejs:python3.9-nodejs15-alpine
  environment:
    APP__ADMIN__PASSWORD: admin
    APP__SYNC_RAW_START_REMOTE_URI: http://opencti-raw-start:4100/graphql
    APP__SYNC_LIVE_START_REMOTE_URI: http://opencti-live-start:4200/graphql
    APP__ADMIN__TOKEN: bfa014e0-e02e-4aa6-a42b-603b19dcf159
    REDIS__HOSTNAME: redis
    ELASTICSEARCH__URL: http://elastic:9200
    MINIO__ENDPOINT: minio
    RABBITMQ__HOSTNAME: rabbitmq
    SMTP__HOSTNAME: smtp.ethereal.email
    SMTP__PORT: 587
    SMTP__USERNAME: jennyfer.mraz@ethereal.email
    SMTP__PASSWORD: frhJ2mSPTfaEutpbug
  commands:
  - apk add build-base git libffi-dev
  - cd opencti-platform/opencti-graphql
  - yarn install
  - yarn build
  - pip3 install --upgrade --force --no-cache-dir git+https://github.com/OpenCTI-Platform/client-python@master
  - yarn test

- name: api-coverage
  image: plugins/codecov
  settings:
    token: e5c6fb05-76f7-4985-86cf-ff843d5d103e
    paths:
      - opencti-platform/opencti-graphql/coverage

- name: frontend-tests
  image: nikolaik/python-nodejs:python3.9-nodejs15-alpine
  commands: 
  - cd opencti-platform/opencti-front
  - yarn install
  - yarn build

- name: build-circleci
  image: curlimages/curl
  commands:
  - curl -X POST --data "branch=master" https://circleci.com/api/v1.1/project/github/OpenCTI-Platform/opencti/build?circle-token=$CIRCLECI_TOKEN
  environment:
    CIRCLECI_TOKEN:
      from_secret: circleci_token
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
      - tag

- name: build-circleci-release
  image: curlimages/curl
  commands:
  - curl -X POST --data "tag=$DRONE_TAG" https://circleci.com/api/v1.1/project/github/OpenCTI-Platform/opencti/build?circle-token=$CIRCLECI_TOKEN
  environment:
    CIRCLECI_TOKEN:
      from_secret: circleci_token
  when:
    event:
      - tag

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    username: drone
    icon_url: https://avatars.githubusercontent.com/oa/1284929
    channel: notifications
  when:
    status: [ success, failure ]
    event:
      exclude:
      - pull_request
    
type:
services:
- name: redis
  image: redis:6.2.5
- name: elastic
  image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
  environment:
    discovery.type: single-node
    ES_JAVA_OPTS: -Xms2g -Xmx2g
- name: minio
  image: minio/minio:RELEASE.2021-09-15T04-54-25Z
  environment:
    MINIO_ROOT_USER: ChangeMe
    MINIO_ROOT_PASSWORD: ChangeMe
  command: [ server, /data ]
- name: rabbitmq
  image: rabbitmq:3.9-management 
- name: opencti-raw-start
  image: nikolaik/python-nodejs:python3.9-nodejs15-alpine
  environment:
    APP__PORT: 4100
    APP__ADMIN__PASSWORD: admin
    APP__ADMIN__TOKEN: bfa014e0-e02e-4aa6-a42b-603b19dcf159
    REDIS__HOSTNAME: redis
    REDIS__NAMESPACE: raw-start
    ELASTICSEARCH__URL: http://elastic:9200
    ELASTICSEARCH__INDEX_PREFIX: raw-start
    MINIO__ENDPOINT: minio
    MINIO__BUCKET_NAME: raw-start-bucket
    RABBITMQ__HOSTNAME: rabbitmq
    SMTP__HOSTNAME: smtp.ethereal.email
    SMTP__PORT: 587
    SMTP__USERNAME: jennyfer.mraz@ethereal.email
    SMTP__PASSWORD: frhJ2mSPTfaEutpbug
  commands:
    - sleep 30
    - apk add build-base git libffi-dev
    - cp -a opencti-platform /tmp/raw-start-platform
    - cd /tmp/raw-start-platform/opencti-graphql
    - yarn install
    - yarn install:python
    - pip3 install --upgrade --force --no-cache-dir git+https://github.com/OpenCTI-Platform/client-python@master
    - yarn start
- name: opencti-live-start
  image: nikolaik/python-nodejs:python3.9-nodejs15-alpine
  environment:
    APP__PORT: 4200
    APP__ADMIN__PASSWORD: admin
    APP__ADMIN__TOKEN: bfa014e0-e02e-4aa6-a42b-603b19dcf159
    REDIS__HOSTNAME: redis
    REDIS__NAMESPACE: live-start
    ELASTICSEARCH__URL: http://elastic:9200
    ELASTICSEARCH__INDEX_PREFIX: live-start
    MINIO__ENDPOINT: minio
    MINIO__BUCKET_NAME: live-start-bucket
    RABBITMQ__HOSTNAME: rabbitmq
    SMTP__HOSTNAME: smtp.ethereal.email
    SMTP__PORT: 587
    SMTP__USERNAME: jennyfer.mraz@ethereal.email
    SMTP__PASSWORD: frhJ2mSPTfaEutpbug
  commands:
    - sleep 60
    - apk add build-base git libffi-dev
    - cp -a opencti-platform /tmp/live-start-platform
    - cd /tmp/live-start-platform/opencti-graphql
    - yarn install
    - yarn install:python
    - pip3 install --upgrade --force --no-cache-dir git+https://github.com/OpenCTI-Platform/client-python@master
    - yarn start