version: 2.1
orbs:
  slack: circleci/slack@4.13.3
  ms-teams: cloudradar-monitoring/ms-teams@0.0.1
  kubernetes: circleci/kubernetes@1.3.1
jobs:
  build_frontend:
    working_directory: ~/opencti
    docker:
      - image: nikolaik/python-nodejs:python3.10-nodejs18
    resource_class: large
    steps:
      - run:
          command: apt-get update --allow-insecure-repositories --allow-unauthenticated && apt-get install -y build-essential libffi-dev curl
      - checkout
      - run:
          working_directory: ~/opencti/opencti-platform/opencti-front
          command: yarn install
      - run:
          working_directory: ~/opencti/opencti-platform/opencti-front
          command: yarn build
          no_output_timeout: 30m
      - run:
          working_directory: ~/
          command: cp -a opencti opencti_docker && cp -a opencti opencti_musl
      - slack/notify:
          event: fail
          template: basic_fail_1
      - ms-teams/report:
          only_on_fail: true
          webhook_url: $MS_TEAMS_WEBHOOK_URL
      - persist_to_workspace:
          root: ~/
          paths:
            - opencti
            - opencti_docker
            - opencti_musl

  build_platform:
    working_directory: ~/opencti
    docker:
      - image: nikolaik/python-nodejs:python3.10-nodejs18
    resource_class: medium+
    steps:
      - run:
          command: apt-get update --allow-insecure-repositories --allow-unauthenticated && apt-get install -y build-essential libffi-dev curl g++ make python3 python3-dev
      - run:
          command: npm install -g node-gyp
      - attach_workspace:
          at: ~/
      - run:
          working_directory: ~/opencti/opencti-platform/opencti-graphql
          command: yarn install
      - run:
          working_directory: ~/opencti/opencti-platform/opencti-graphql
          command: yarn build
      - slack/notify:
          event: fail
          template: basic_fail_1
      - ms-teams/report:
          only_on_fail: true
          webhook_url: $MS_TEAMS_WEBHOOK_URL          
      - persist_to_workspace:
          root: ~/
          paths:
            - opencti

  docker_build_platform:
    working_directory: ~/opencti_docker
    machine:
      image: ubuntu-2004:202111-02
      resource_class: large
    environment:
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/amd64,linux/arm64
    steps:
      - attach_workspace:
          at: ~/
      - run: sudo apt-get update -qq && sudo apt install curl
      - run:
          name: Install buildx
          command: |
            BUILDX_BINARY_URL="https://github.com/docker/buildx/releases/download/v0.8.2/buildx-v0.8.2.linux-amd64"
            curl --output docker-buildx \
              --silent --show-error --location --fail --retry 3 \
              "$BUILDX_BINARY_URL"
            mkdir -p ~/.docker/cli-plugins
            mv docker-buildx ~/.docker/cli-plugins/
            chmod a+x ~/.docker/cli-plugins/docker-buildx
            docker buildx install
            # Run binfmt
            docker run --rm --privileged tonistiigi/binfmt:latest --install "$BUILDX_PLATFORMS"
            docker buildx create --name mybuilder --use
      - run:
          name: Login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          working_directory: ~/opencti_docker/opencti-platform
          name: Build Docker image opencti/platform
          command: docker buildx build --platform $BUILDX_PLATFORMS -f Dockerfile_circleci -t opencti/platform:${CIRCLE_TAG} --push .
          no_output_timeout: 30m
      - slack/notify:
          event: fail
          template: basic_fail_1
      - ms-teams/report:
          only_on_fail: true
          webhook_url: $MS_TEAMS_WEBHOOK_URL

  docker_build_worker:
    working_directory: ~/opencti_docker
    machine:
      image: ubuntu-2004:202111-02
      resource_class: large
    environment:
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/amd64,linux/arm64
    steps:
      - attach_workspace:
          at: ~/
      - run: sudo apt-get update -qq && sudo apt install curl       
      - run:
          name: Install buildx
          command: |
            BUILDX_BINARY_URL="https://github.com/docker/buildx/releases/download/v0.8.2/buildx-v0.8.2.linux-amd64"
            curl --output docker-buildx \
              --silent --show-error --location --fail --retry 3 \
              "$BUILDX_BINARY_URL"
            mkdir -p ~/.docker/cli-plugins
            mv docker-buildx ~/.docker/cli-plugins/
            chmod a+x ~/.docker/cli-plugins/docker-buildx
            docker buildx install
            # Run binfmt
            docker run --rm --privileged tonistiigi/binfmt:latest --install "$BUILDX_PLATFORMS"
            docker buildx create --name mybuilder --use
      - run:
          name: Login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          working_directory: ~/opencti_docker/opencti-worker
          name: Build Docker image opencti/worker
          command: docker buildx build --platform $BUILDX_PLATFORMS -t opencti/worker:${CIRCLE_TAG} --push .
      - slack/notify:
          event: fail
          template: basic_fail_1
      - ms-teams/report:
          only_on_fail: true
          webhook_url: $MS_TEAMS_WEBHOOK_URL     

workflows:
  opencti:
    jobs:
      - build_frontend:
          filters:
            tags:
              only: /.*/
      - build_platform:
          filters:
            tags:
              only: /.*/
          requires:
            - build_frontend
      - docker_build_platform:
          requires:
            - build_frontend
          filters:
            tags:
              only: filigran-beta-denorm6
            branches:
              ignore: /.*/
      - docker_build_worker:
          requires:
            - build_frontend
          filters:
            tags:
              only: filigran-beta-denorm6
            branches:
              ignore: /.*/