version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    # volumes:
    #   - esdata-dev:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.ml.enabled=false
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    restart: unless-stopped
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    # volumes:
    #   - amqpdata-dev:/var/lib/rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
  
  redis:
    image: redis:6.2.5
    container_name: redis
    restart: unless-stopped
    # volumes:
    #   - redisdata-dev:/data
    ports:
      - 6379:6379

# volumes:
#   esdata-dev:
#   redisdata-dev:
#   amqpdata-dev: