version: '3'

services:
  opencti-dev-redis:
    image: redis:6.2.5
    container_name: opencti-dev-redis
    restart: unless-stopped
    ports:
      - 6379:6379
  
  opencti-dev-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: opencti-dev-elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms4G -Xmx4G"
      - xpack.ml.enabled=false
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
      - 9300:9300
  
  opencti-dev-kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    container_name: opencti-dev-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://opencti-dev-elasticsearch:9200
    restart: unless-stopped
    ports:
      - 5601:5601
    depends_on:
      - opencti-dev-elasticsearch
  
  opencti-dev-rabbitmq:
    image: rabbitmq:3.9-management
    container_name: opencti-dev-rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
