version: '3'

services:
  redis:
    image: redis:6.2.5
    container_name: redis
    restart: unless-stopped
    volumes:
      - redisdata:/data
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.ml.enabled=false
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=GUEST
      - RABBITMQ_DEFAULT_PASS=GUEST
    volumes:
      - amqpdata:/var/lib/rabbitmq
    restart: unless-stopped
  
  opencti:
    image: docker.darklight.ai/opencti:5.0.1
    container_name: opencti
    environment:
      - NODE_OPTIONS=--max-old-space-size=8096
      - APP__PORT=8080
      - APP__ADMIN__EMAIL=admin@opencti.io
      - APP__ADMIN__PASSWORD=opencti
      - APP__ADMIN__TOKEN=0928d607-2abe-4b59-8c92-1ec9b565f3a7
      - APP__APP_LOGS__LOGS_LEVEL=error
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - ELASTICSEARCH__URL=http://localhost:9200
      - MINIO__ENDPOINT=minio
      - MINIO__PORT=9000
      - MINIO__USE_SSL=false
      - MINIO__ACCESS_KEY=yoshida
      - MINIO__SECRET_KEY=torajiro
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=admin
      - RABBITMQ__PASSWORD=adminpass
      - SMTP__HOSTNAME=${SMTP_HOSTNAME}
      - SMTP__PORT=25
      - PROVIDERS__LOCAL__STRATEGY=LocalStrategy
      - SUBSCRIPTION_SCHEDULER__ENABLED=false
      # - PROVIDERS__OPENID__STRATEGY=OpenIDConnectStrategy 
      # - "PROVIDERS__OPENID__CONFIG__LABEL=Login with OpenID"
      # - PROVIDERS__OPENID__CONFIG__ISSUER=${OPENID_ISSUER}
      # - PROVIDERS__OPENID__CONFIG__CLIENT_ID=${OPENID_CLIENT_ID}
      # - PROVIDERS__OPENID__CONFIG__CLIENT_SECRET=${OPENID_CLIENT_SECRET}
      # - "PROVIDERS__OPENID__CONFIG__REDIRECT_URIS=[\"https://demo.opencti.io/auth/oic/callback\"]"
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - elasticsearch
      - rabbitmq
    restart: unless-stopped

volumes:
  esdata:
  redisdata:
  amqpdata:
