version: '3'

services:
  redis:
    image: redis:6.2.5
    container_name: redis
    restart: unless-stopped
    volumes:
      - redisdata:/data
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.ml.enabled=false
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - amqpdata:/var/lib/rabbitmq
    restart: unless-stopped
  
  opencti:
    image: docker.darklight.ai/opencti
    build: ../opencti-platform
    container_name: opencti
    environment:
      - NODE_OPTIONS=--max-old-space-size=8096
      - APP__PORT=8080
      - APP__ADMIN__EMAIL=${OPENCTI_ADMIN_EMAIL}
      - APP__ADMIN__PASSWORD=${OPENCTI_ADMIN_PASSWORD}
      - APP__ADMIN__TOKEN=${OPENCTI_ADMIN_TOKEN}
      - APP__APP_LOGS__LOGS_LEVEL=error
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - ELASTICSEARCH__URL=http://elasticsearch:9200
      - MINIO__ENDPOINT=minio
      - MINIO__PORT=9000
      - MINIO__USE_SSL=false
      - MINIO__ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO__SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - SMTP__HOSTNAME=${SMTP_HOSTNAME}
      - SMTP__PORT=25
      - PROVIDERS__LOCAL__STRATEGY=LocalStrategy
      - SUBSCRIPTION_SCHEDULER__ENABLED=false
      # - PROVIDERS__OPENID__STRATEGY=OpenIDConnectStrategy 
      # - "PROVIDERS__OPENID__CONFIG__LABEL=Login with OpenID"
      # - PROVIDERS__OPENID__CONFIG__ISSUER=${OPENID_ISSUER}
      # - PROVIDERS__OPENID__CONFIG__CLIENT_ID=${OPENID_CLIENT_ID}
      # - PROVIDERS__OPENID__CONFIG__CLIENT_SECRET=${OPENID_CLIENT_SECRET}
      # - "PROVIDERS__OPENID__CONFIG__REDIRECT_URIS=[\"https://demo.opencti.io/auth/oic/callback\"]"
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - elasticsearch
      - rabbitmq
    restart: unless-stopped
  
  graphql:
    image: docker.darklight.ai/graphql
    build: ./graphql
    container_name: graphql
    restart: unless-stopped
    working_dir: /graphql
    entrypoint: node ./src/index.js
    volumes:
      - "./graphql:/graphql"
    ports:
      - "4000:4000"

volumes:
  esdata:
  redisdata:
  amqpdata:
