version: '3'

services:
  redis:
    image: redis:6.2.5
    container_name: redis
    restart: unless-stopped
    volumes:
      - redisdata:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.ml.enabled=false
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - amqpdata:/var/lib/rabbitmq
    restart: unless-stopped

  opencti:
    image: docker.darklight.ai/opencti
    build: ../opencti-platform
    container_name: opencti
    environment:
      - NODE_OPTIONS=--max-old-space-size=8096
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - MOCKS=${MOCKS}
      - APP__PORT=8080
      - APP__ADMIN__EMAIL=${OPENCTI_ADMIN_EMAIL}
      - APP__ADMIN__PASSWORD=${OPENCTI_ADMIN_PASSWORD}
      - APP__ADMIN__TOKEN=${OPENCTI_ADMIN_TOKEN}
      - APP__APP_LOGS__LOGS_LEVEL=error
      # - APP__HTTPS_CERT__KEY=/opt/opencti/certs/darklight.key
      # - APP__HTTPS_CERT__CRT=/opt/opencti/certs/darklight.crt
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - ELASTICSEARCH__URL=http://elasticsearch:9200
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - SMTP__HOSTNAME=${SMTP_HOSTNAME}
      - SMTP__PORT=25
      - PROVIDERS__LOCAL__STRATEGY=LocalStrategy
      - SUBSCRIPTION_SCHEDULER__ENABLED=false
      # - PROVIDERS__OPENID__STRATEGY=OpenIDConnectStrategy
      # - "PROVIDERS__OPENID__CONFIG__LABEL=Login with OpenID"
      # - PROVIDERS__OPENID__CONFIG__ISSUER=${OPENID_ISSUER}
      # - PROVIDERS__OPENID__CONFIG__CLIENT_ID=${OPENID_CLIENT_ID}
      # - PROVIDERS__OPENID__CONFIG__CLIENT_SECRET=${OPENID_CLIENT_SECRET}
      # - "PROVIDERS__OPENID__CONFIG__REDIRECT_URIS=[\"https://demo.opencti.io/auth/oic/callback\"]"
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - elasticsearch
      - rabbitmq
    restart: unless-stopped
    # volumes:
    #   - ./default.json:/opt/opencti/config/default.json
    #   - ./darklight.crt:/opt/opencti/certs/darklight.crt
    #   - ./darklight.key:/opt/opencti/certs/darklight.key

volumes:
  esdata:
  redisdata:
  amqpdata:
