version: '3'

services:
  redis:
    image: redis:6.2.5
    container_name: redis
    ports:
      - "6379:6379"
    profiles:
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Dlog4j2.formatMsgNoLookups=true"
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    profiles:
      - backend

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rodger
      - RABBITMQ_DEFAULT_PASS=rabbit
    ports:
      - "5672:5672"
    profiles:
      - backend

  stardog:
    image: docker.darklight.ai/stardog:7.9.0
    container_name: stardog
    restart: unless-stopped
    environment:
      STARDOG_USER: admin
      STARDOG_PASSWORD: admin
    ports:
      - "15820:5820"
    volumes:
      - "./stardog-license-key.bin:/var/opt/stardog/stardog-license-key.bin"
    profiles:
      - stardog

  cyio:
    image: docker.darklight.ai/opencti:${CYIO_TAG:-latest}
    container_name: cyio
    hostname: cyio-localhost.darklight.ai
    restart: unless-stopped
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - NODE_OPTIONS=--max-old-space-size=8096
    ports:
      - "4000:4000"
    volumes:
      - ./default.json:/opt/opencti/config/default.json
      - ./opencti-front-localhost.crt:/opt/opencti/certs/darklight.crt
      - ./opencti-front-localhost.key:/opt/opencti/certs/darklight.key
    profiles:
      - frontend
